### ISSUE TITLE
Fails when passing pathlib.Path object

### ISSUE THREAD

**Issue by stefan6419846** [dlenski/python-zxing#35]
Passing a `pathlib.Path` object as the `filenames` parameter raises some error:

```python3
Traceback (most recent call last):
  File "/home/stefan/temp/run.py", line 57, in <module>
    print(reader.decode(path))
  File "/home/stefan/temp/venv/lib/python3.9/site-packages/zxing/__init__.py", line 80, in decode
    for fn_or_im in filenames:
TypeError: 'PosixPath' object is not iterable
```

https://github.com/dlenski/python-zxing/blob/ea517d0a7326b12a8a7492d3a0c73513c46a6ef5/zxing/__init__.py#L72-L76 seems to be incomplete and probably should check for the inverse, id est for known iterables.

**Comment by dlenski** [comment]
> seems to be incomplete and probably should check for the inverse, id est for known iterables

Want to submit a PR to do it this way instead?
